FROM nginx:1.10

ADD vhost.conf /etc/nginx/conf.d/default.conf

CMD if [ -f index.php ]; then \
        rm index.php &&\
        mv /tmp/project/* /var/www/html/ && \
        mv /tmp/project/.* /var/www/html/ | : &&\
        php artisan config:clear &&\
        php artisan cache:clear ; \
    fi &&\
    chown -R nginx:nginx /var/www/app/storage
    echo "Try connect to db and set up schema..." && \
    php artisan migrate --seed --force &&\
    /start.sh

chown -R nginx:nginx /var/www/app/storage
